{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "ename": "ConnectionError",
     "evalue": "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "In  \u001b[0;34m[18]\u001b[0m:\nLine \u001b[0;34m14\u001b[0m:    j = requests.get(baseURL)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\requests\\api.py\u001b[0m, in \u001b[0;32mget\u001b[0m:\nLine \u001b[0;34m75\u001b[0m:    \u001b[34mreturn\u001b[39;49;00m request(\u001b[33m'\u001b[39;49;00m\u001b[33mget\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m, url, params=params, **kwargs)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\requests\\api.py\u001b[0m, in \u001b[0;32mrequest\u001b[0m:\nLine \u001b[0;34m61\u001b[0m:    \u001b[34mreturn\u001b[39;49;00m session.request(method=method, url=url, **kwargs)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\requests\\sessions.py\u001b[0m, in \u001b[0;32mrequest\u001b[0m:\nLine \u001b[0;34m529\u001b[0m:   resp = \u001b[36mself\u001b[39;49;00m.send(prep, **send_kwargs)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\requests\\sessions.py\u001b[0m, in \u001b[0;32msend\u001b[0m:\nLine \u001b[0;34m645\u001b[0m:   r = adapter.send(request, **kwargs)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site-packages\\requests\\adapters.py\u001b[0m, in \u001b[0;32msend\u001b[0m:\nLine \u001b[0;34m501\u001b[0m:   \u001b[34mraise\u001b[39;49;00m \u001b[36mConnectionError\u001b[39;49;00m(err, request=request)\n",
      "\u001b[0;31mConnectionError\u001b[0m: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "import arcpy\n",
    "import urllib3\n",
    "import json\n",
    "import requests\n",
    "# Setup\n",
    "\n",
    "arcpy.env.overwriteOutput = True\n",
    "baseURL = \"https://maps.byui.edu/arcgis/rest/services/Building/Floorplan_Room_Reference/FeatureServer/1\"\n",
    "fields = \"*\"\n",
    "outdata = \"D:/coding/IT_ticket_automation/\"\n",
    "\n",
    "# Get record extract limit\n",
    "urlstring = baseURL + \"?f=json\"\n",
    "j = requests.get(baseURL)\n",
    "js = json.load(j)\n",
    "maxrc = int(js[\"maxRecordCount\"])\n",
    "print(\"Record extract limit: %s\" % maxrc)\n",
    "\n",
    "# Get object ids of features\n",
    "where = \"1=1\"\n",
    "urlstring = baseURL + \"/query?where={}&returnIdsOnly=true&f=json\".format(where)\n",
    "j = requests.get(urlstring)\n",
    "js = json.load(j)\n",
    "idfield = js[\"objectIdFieldName\"]\n",
    "idlist = js[\"objectIds\"]\n",
    "idlist.sort()\n",
    "numrec = len(idlist)\n",
    "print(\"Number of target records: %s\" % numrec)\n",
    "\n",
    "# Gather features\n",
    "print(\"Gathering records...\")\n",
    "fs = dict()\n",
    "for i in range(0, numrec, maxrc):\n",
    "  torec = i + (maxrc - 1)\n",
    "  if torec > numrec:\n",
    "    torec = numrec - 1\n",
    "  fromid = idlist[i]\n",
    "  toid = idlist[torec]\n",
    "  where = \"{} >= {} and {} <= {}\".format(idfield, fromid, idfield, toid)\n",
    "  print(\"  {}\".format(where))\n",
    "  urlstring = baseURL + \"/query?where={}&returnGeometry=true&outFields={}&f=json\".format(where,fields)\n",
    "  fs[i] = arcpy.FeatureSet()\n",
    "  fs[i].load(urlstring)\n",
    "\n",
    "# Save features\n",
    "print(\"Saving features...\")\n",
    "fslist = []\n",
    "for key,value in fs.items():\n",
    "  fslist.append(value)\n",
    "arcpy.Merge_management(fslist, outdata)\n",
    "print(\"Done!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "ename": "URLError",
     "evalue": "<urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mURLError\u001b[0m                                  Traceback (most recent call last)",
      "In  \u001b[0;34m[24]\u001b[0m:\nLine \u001b[0;34m25\u001b[0m:    j = urllib.request.urlopen(urlstring)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32murlopen\u001b[0m:\nLine \u001b[0;34m214\u001b[0m:   \u001b[34mreturn\u001b[39;49;00m opener.open(url, data, timeout)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32mopen\u001b[0m:\nLine \u001b[0;34m517\u001b[0m:   response = \u001b[36mself\u001b[39;49;00m._open(req, data)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32m_open\u001b[0m:\nLine \u001b[0;34m534\u001b[0m:   result = \u001b[36mself\u001b[39;49;00m._call_chain(\u001b[36mself\u001b[39;49;00m.handle_open, protocol, protocol +\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32m_call_chain\u001b[0m:\nLine \u001b[0;34m494\u001b[0m:   result = func(*args)\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32mhttps_open\u001b[0m:\nLine \u001b[0;34m1389\u001b[0m:  \u001b[34mreturn\u001b[39;49;00m \u001b[36mself\u001b[39;49;00m.do_open(http.client.HTTPSConnection, req,\n",
      "File \u001b[0;34mC:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\urllib\\request.py\u001b[0m, in \u001b[0;32mdo_open\u001b[0m:\nLine \u001b[0;34m1349\u001b[0m:  \u001b[34mraise\u001b[39;49;00m URLError(err)\n",
      "\u001b[0;31mURLError\u001b[0m: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m"
     ]
    }
   ],
   "source": [
    "import arcpy\n",
    "\n",
    "import urllib.request, urllib.error, urllib.parse\n",
    "\n",
    "import json\n",
    "\n",
    "\n",
    "\n",
    "# Setup\n",
    "\n",
    "arcpy.env.overwriteOutput = True\n",
    "\n",
    "baseURL = \"https://maps.byui.edu/arcgis/rest/services/Building/Floorplan_Room_Reference/FeatureServer\"\n",
    "\n",
    "fields = \"*\"\n",
    "\n",
    "outdata = \"D:/coding/IT_ticket_automation/\"\n",
    "\n",
    "\n",
    "\n",
    "# Get record extract limit\n",
    "\n",
    "urlstring = baseURL + \"?f=json\"\n",
    "\n",
    "j = urllib.request.urlopen(urlstring)\n",
    "\n",
    "js = json.load(j)\n",
    "\n",
    "maxrc = 10000\n",
    "\n",
    "print(\"Record extract limit: %s\" % maxrc)\n",
    "\n",
    "\n",
    "\n",
    "# Get object ids of features\n",
    "\n",
    "where = \"1=1\"\n",
    "\n",
    "urlstring = baseURL + \"/query?where={}&returnIdsOnly=true&f=json\".format(where)\n",
    "\n",
    "j = urllib.request.urlopen(urlstring)\n",
    "\n",
    "js = json.load(j)\n",
    "\n",
    "idfield = js[\"objectIdFieldName\"]\n",
    "\n",
    "idlist = js[\"objectIds\"]\n",
    "\n",
    "idlist.sort()\n",
    "\n",
    "numrec = len(idlist)\n",
    "\n",
    "print(\"Number of target records: %s\" % numrec)\n",
    "\n",
    "\n",
    "\n",
    "# Gather features\n",
    "\n",
    "print(\"Gathering records...\")\n",
    "\n",
    "fs = dict()\n",
    "\n",
    "for i in range(0, numrec, maxrc):\n",
    "\n",
    "    torec = i + (maxrc - 1)\n",
    "\n",
    "    if torec > numrec:\n",
    "\n",
    "        torec = numrec - 1\n",
    "\n",
    "        fromid = idlist[i]\n",
    "\n",
    "        toid = idlist[torec]\n",
    "\n",
    "        where = \"{} >= {} and {} <= {}\".format(idfield, fromid, idfield, toid)\n",
    "\n",
    "        print(\" {}\".format(where))\n",
    "\n",
    "urlstring = baseURL + \"/query?where={}&returnGeometry=true&outFields={}&f=json\".format(where,fields)\n",
    "\n",
    "fs[i] = arcpy.FeatureSet()\n",
    "\n",
    "fs[i].load(urlstring)\n",
    "\n",
    "\n",
    "\n",
    "# Save features\n",
    "\n",
    "print(\"Saving features...\")\n",
    "\n",
    "fslist = []\n",
    "\n",
    "for key,value in list(fs.items()):\n",
    "\n",
    "    fslist.append(value)\n",
    "\n",
    "    arcpy.Merge_management(fslist, outdata)\n",
    "\n",
    "print(\"Done!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fatal Python error: init_import_size: Failed to import the site module\n",
      "Python runtime state: initialized\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site.py\", line 73, in <module>\n",
      "    import os\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\os.py\", line 29, in <module>\n",
      "    from _collections_abc import _check_methods\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\_collections_abc.py\", line 12, in <module>\n",
      "    GenericAlias = type(list[int])\n",
      "TypeError: 'type' object is not subscriptable\n"
     ]
    }
   ],
   "source": [
    "!conda install urllib3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Fatal Python error: init_import_size: Failed to import the site module\n",
      "Python runtime state: initialized\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\site.py\", line 73, in <module>\n",
      "    import os\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\os.py\", line 29, in <module>\n",
      "    from _collections_abc import _check_methods\n",
      "  File \"C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\arcgispro-py3\\Lib\\_collections_abc.py\", line 12, in <module>\n",
      "    GenericAlias = type(list[int])\n",
      "TypeError: 'type' object is not subscriptable\n"
     ]
    }
   ],
   "source": [
    "!pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ArcGISPro",
   "language": "Python",
   "name": "python3"
  },
  "language_info": {
   "file_extension": ".py",
   "name": "python",
   "version": "3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
